---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkinds-data
  namespace: jenkinds
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path  # k3s default storage class
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkinds-logs
  namespace: jenkinds
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: jenkinds
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
