---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkinds-sa
  namespace: jenkinds
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkinds-role
  namespace: jenkinds
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkinds-rolebinding
  namespace: jenkinds
subjects:
- kind: ServiceAccount
  name: jenkinds-sa
  namespace: jenkinds
roleRef:
  kind: Role
  name: jenkinds-role
  apiGroup: rbac.authorization.k8s.io
