---
apiVersion: v1
kind: Secret
metadata:
  name: jenkinds-secrets
  namespace: jenkinds
type: Opaque
stringData:
  # Jenkins Credentials
  JENKINS_URL: "https://your-jenkins.com"
  JENKINS_USER: "your-username"
  JENKINS_API_TOKEN: "your-api-token"
  
  # OpenAI
  OPENAI_API_KEY: "sk-your-openai-key-here"
  
  # JWT Secrets (CHANGE THESE!)
  JWT_SECRET: "your-super-secret-jwt-key-change-this-in-production"
  REFRESH_TOKEN_SECRET: "your-refresh-token-secret-change-this-in-production"
  
  # Email (Optional)
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: "your-email@gmail.com"
  SMTP_PASSWORD: "your-password"
  EMAIL_FROM: "noreply@jenkinds.io"
  
  # Sentry (Optional)
  SENTRY_DSN: ""
